name: CI/CD to EC2 without Docker

on:
  push:
    branches: [ dev ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    #하하하하하 test16
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle (without tests)
        run: ./gradlew clean build -x test

      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add EC2 host to known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.DEPLOY_HOST }} >> ~/.ssh/known_hosts

      - name: Print Remote_APP_PATH
        run: echo "${{ secrets.REMOTE_APP_PATH }}"

      - name: Copy file to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          source: "build/libs/heattech-0.0.1-SNAPSHOT.jar"
          target: "${{ secrets.REMOTE_APP_PATH }}"

      - name: Restart service on server
        run: |
          ssh ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }} << 'EOF'
            cd ${{ secrets.REMOTE_APP_PATH }}
            pids=$(pgrep -f 'java -jar')
            if [ -n "$pids" ]; then
            kill -9 $pids
          fi
            nohup java -jar heattech-0.0.1-SNAPSHOT.jar > ${{ secrets.REMOTE_APP_PATH }}/heattech.log 2>&1 &
            exit
          EOF
