name: CI/CD to EC2 (EC2에서 직접 빌드)

#dev 브랜치에 push가 일어나면 실행
on:
  push:
    branches: [ dev ]

jobs:
  build-and-deploy: #build, deploy 할거임
    runs-on: ubuntu-latest #깃허브가 제공하는 Ubuntu 서버에서 실행

    #단계 명세
    steps:
      #깃허브 컴퓨터에 ssh 비밀키 세팅
      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      #.ssh 폴더 만들고 등록
      - name: Add EC2 host to known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.DEPLOY_HOST }} >> ~/.ssh/known_hosts
      #ec2 접속 후 dev 브랜치 코드 가져오기, 빌드, 원래 실행 중이던 서버 종료 후 실행
      - name: Deploy and restart service on EC2
        run: |
          ssh ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }} << EOF
            set -e
            cd ${{ secrets.REMOTE_APP_PATH }}
            git pull origin dev
            ./gradlew clean build -x test > build.log 2>&1
            cat build.log
            echo "빌드 성공, JAR 확인"
            if [ ! -f build/libs/heattech-0.0.1-SNAPSHOT.jar ]; then
              echo "❌ JAR 파일 생성 실패!"
              exit 1
            fi
            echo "JAR 있음, 서버 프로세스 종료 시도"
            pids=\$(pgrep -f 'java -jar')
            if [ -n "\$pids" ]; then
              kill -9 \$pids
              echo "기존 서버 종료"
            fi
            echo "새 서버 실행"
            nohup java -jar build/libs/heattech-0.0.1-SNAPSHOT.jar > heattech.log 2>&1 &
            echo "서버 실행 완료"
          EOF
