name: CI/CD to EC2 without Docker

on:
  push:
    branches: [ dev ] #dev 브랜치에 push 될 때마다 동작

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      #소스코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v3
      #JDK 세팅
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      # gradlew에 실행 권한 부여
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew


      - name: Build with Gradle (without tests)
        run: ./gradlew clean build -x test

          # 4. EC2에 jar, shell script 등 파일 전송
      - name: Copy files to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          source: "build/libs/heattech-0.0.1-SNAPSHOT.jar"
          target: ${{ secrets.REMOTE_APP_PATH }}

      g

      # 서버 종료, 최신코드 업데이트, 재실행
      - name: Deploy on EC
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set +e
            cd ${{ secrets.REMOTE_APP_PATH }}
            echo "1. 기존 서버 종료"
            pkill -f "java -jar build/libs/heattech-0.0.1-SNAPSHOT.jar" || true

            echo "2. 최신 코드 Pull"
            git pull origin dev

            echo "3. 빌드 & jar 생성"
            ./gradlew clean build -x test

            echo "4. 서버 백그라운드 실행"
            nohup java -jar build/libs/heattech-0.0.1-SNAPSHOT.jar > heattech.log 2>&1 &