name: CI/CD to EC2 without Docker

on:
  push:
    branches: [ dev ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    #하하하
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle (without tests)
        run: ./gradlew clean build -x test

      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add EC2 host to known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.DEPLOY_HOST }} >> ~/.ssh/known_hosts

      - name: Copy JAR to server
        run: |
          scp -v build/libs/heattech-0.0.1-SNAPSHOT.jar ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }}:${{ secrets.REMOTE_APP_PATH }}/heattech-0.0.1-SNAPSHOT.jar

      - name: Restart service on server
        run: |
          ssh ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }} << 'EOF'
            pkill -f 'java -jar' || true
            nohup java -jar ${{ secrets.REMOTE_APP_PATH }}/heattech-0.0.1-SNAPSHOT.jar > ${{ secrets.REMOTE_APP_PATH }}/heattech.log 2>&1 &
            exit
          EOF
