name: CI/CD to EC2 (EC2에서 직접 빌드)

on:
  push:
    branches: [ dev ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21

      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add EC2 host to known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.DEPLOY_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy and restart service on EC2
        run: |
          ssh ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }} << 'EOF'
            set -e
            cd ${{ secrets.REMOTE_APP_PATH }}
            git pull origin dev
            ./gradlew clean build -x test > build.log 2>&1
            cat build.log
            if [ ! -f build/libs/heattech-0.0.1-SNAPSHOT.jar ]; then
              echo "❌ JAR 파일 생성 실패!"
              exit 1
            fi
            pids=\$(pgrep -f 'java -jar')
            if [ -n "\$pids" ]; then
              kill -9 \$pids
            fi
            nohup java -jar build/libs/heattech-0.0.1-SNAPSHOT.jar > heattech.log 2>&1 &
            exit
          EOF
