name: CI/CD to EC2 without Docker

on:
  push:
    branches: [ dev ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Grant execute permission to Gradle
        run: chmod +x gradlew

      - name: Build with Gradle (without tests)
        run: ./gradlew clean build -x test

      - name: Copy .jar to EC2
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "build/libs/*.jar"
          target: "~/app"

      - name: SSH into EC2 and restart app
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "🔻 이전 프로세스 종료 중..."
            pkill -f 'java -jar' || true
            
            echo "🧹 기존 jar 정리..."
            rm -f ~/app/app.jar
            
            echo "📦 최신 jar 이름 변경..."
            mv ~/app/*.jar ~/app/app.jar
            
            echo "🚀 새 프로세스 실행 시작..."
            nohup java -jar ~/app/app.jar --spring.profiles.active=prod > ~/heattech.log 2>&1 &
            
            echo "✅ 실행 완료. 로그는 ~/heattech.log 에 저장됨"